version: "3.9"  # optional since v1.27.0
services:
  web:
    image: darkander/actionnode
    environment:
      - SALT=10
      - SECRET='MYAPP'
      - DATABASE_URL=postgresql://prisma:prisma@postgres-db:5432/dev?schema=public
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data2
    ports:
      - '5432:5432'
volumes:
  postgres:
