version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .env.:/app/.env
  postgres-db:
    image: postgres:10.3
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:
