name: Container
on: push
jobs:
  run-container:
    runs-on: ubuntu-latest
    services:
      web:
        image: darkander/actionnode
        env:
          SALT: 10
          SECRET: MYAPP
          DATABASE_URL: postgresql://prisma:prisma@postgres-db:5432/dev?schema=public
        ports:
          - "8000:8000"
      postgres-db:
        image: postgres
        env:
          POSTGRES_USER: prisma
          POSTGRES_PASSWORD: prisma
        volumes:
          - postgres:/var/lib/postgresql/data2
        ports:
          - '5432:5432'
    steps:
      - name: Register
        run: 'curl -X POST http://localhost:8000/users/register -H ''Content-Type: application/json'' --data-raw ''{
        "email": "andrif@gmail.com",
        "name": "andriy",
        "password": "1234"
        }'''
