name: Matrix
on: push
jobs:
  node-version:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [6,8,10]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Node Version
        run: node -v
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Node Version
        run: node -v
